openapi: 3.0.0
info:
  version: '1'
  title: Smart-Home API
  description: no description
servers:
  - url: http://api-esp32-smarthome.local

paths:
  /led:
    get:
      tags:
        - SmartHome
      operationId: GET_led
      summary: Get LED
      description: Change status of the LED with the given color.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/led-result-object'
        '404':
          $ref: '#/components/responses/trait_standardErrors_404'
      parameters:
        - name: color
          in: query
          required: true
          schema:
            type: string
          description: Specify the color of the led to change.
        - name: state
          in: query
          required: true
          schema:
            type: string
          description: Specify wanted state of the led. OFF - off, ON - on.

  /led-status:
    get:
      tags:
        - SmartHome
      operationId: GET_led_status
      summary: Get LED status
      description: Get the status of the LED with the given color. Only tells the status of the led with no changes.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/led-result-object'
        '404':
          $ref: '#/components/responses/trait_standardErrors_404'
      parameters:
        - name: color
          in: query
          required: true
          schema:
            type: string
          description: Specify the color of the led to get it's status.

  /lcd:
    get:
      tags:
        - SmartHome
      operationId: GET_lcd
      summary: Get LCD message
      description: Get the current message on the LCD screen.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lcd-result-object'
        '404':
          $ref: '#/components/responses/trait_standardErrors_404'
    post:
      tags:
        - SmartHome
      operationId: POST_lcd
      summary: Post onto LCD screen
      description: Post an ASCII-string message on the LCD screen.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lcd-result-object'
        '404':
          $ref: '#/components/responses/trait_standardErrors_404'
        '400':
          $ref: '#/components/responses/trait_sessionErrors_400'
      requestBody:
        $ref: '#/components/requestBodies/POST_lcd-body'

  /get-all:
    get:
      tags:
        - SmartHome
      operationId: GET_get-all-status
      summary: Get status of all devices
      description: Get status of all connected devices.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  led:
                    type: array
                    items:
                      $ref: "#/components/schemas/led-result-object"
                  lcd:
                    $ref: "#/components/schemas/lcd-result-object"
                  tempature:
                    $ref: "#/components/schemas/temperature-result-object"
                  potentiometer:
                    $ref: "#/components/schemas/potentiometer-result-object"
        '404':
          $ref: '#/components/responses/trait_standardErrors_404'

  /temperature:
    get:
      tags:
        - SmartHome
      operationId: GET_temperature
      summary: Get temperature
      description: Get the current temperature, in Celsius or Fahrenheit.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/temperature-result-object'
        '404':
          $ref: '#/components/responses/trait_standardErrors_404'

  /potentiometer:
    get:
      tags:
        - SmartHome
      operationId: GET_potentiometer
      summary: Get potentiometer
      description: Get the current value of the potentiometer in Ohm.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/potentiometer-result-object'
        '404':
          $ref: '#/components/responses/trait_standardErrors_404'

components:  
  responses:
    trait_standardErrors_404:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    
    trait_sessionErrors_400:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
  
  requestBodies:
    POST_lcd-body:
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Hello World!"
            required:
              - message
  schemas:
    led-result-object:
      title: led-result-object
      type: object
      properties:
        color:
          type: string
        status:
          type: string
    
    lcd-result-object:
      title: lcd-result-object
      type: object
      properties:
        message:
          type: string
      
    temperature-result-object:
      title: temperature-result-object
      type: object
      properties:
        farhenheit:
          type: number
        celsius:
          type: number

    potentiometer-result-object:
      title: potentiometer-result-object
      type: object
      properties:
        resistance:
          type: number
